name: Generate PlantUML Diagrams
uses: holowinski/plantuml-github-action@main

on:
  push:

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg $(find . -name '*.puml')
