name: Generate JavaScript state machines from PlantUML using StateSmith
on:
  push:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

jobs:
  statesmith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download ss.cli
        run: |
          curl -sSL -o ss.cli https://github.com/StateSmith/StateSmith/releases/download/cli-v0.17.4/ss.cli-linux-x64
          chmod a+x ss.cli
          ls -l 
          ./ss.cli --version

      - name: Generate JavaScript state machines using statesmith
        run: |
          find . -name 'lightbulb*'
          ./ss.cli run --lang=JavaScript --no-ask --no-csx -hr -b
          find . -name 'lightbulb*'
          
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate JS for state machines using StateSmith"
          branch: ${{ github.head_ref }}
