name: Generate JavaScript state machines from PlantUML using StateSmith

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab (FOR TESTING)
  workflow_dispatch:

jobs:
  statesmith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download ss.cli
        run: |
          curl -sSL -o ss.cli https://github.com/StateSmith/StateSmith/releases/download/cli-v0.17.4/ss.cli-linux-x64
          chmod a+x ss.cli
          ls -l 
          ./ss.cli --version

          
      - name: Generate JavaScript state machines using statesmith
        run: ./ss.cli run --lang=JavaScript -hr --no-ask --no-csx
